<?php
$var = 0;
echo $var += 20;
echo '<br />';
echo $var *= 2;
echo '<br />';
echo $var -= 4;
echo '<br />';
echo $var /= 9;
echo '<br />';
echo $var *= $var;
echo '<br />';
echo $var %= 7;
echo '<br />';
echo '=================';
echo '<br />';
$str = 'Я обожаю ';
$str .= 'изучать ';
$str .= 'PHP!';
echo $str;
